// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnflirlrujdtemgsjzds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZmxpcmxydWpkdGVtZ3NqemRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjg3MzcsImV4cCI6MjA2OTY0NDczN30.4BSVtbbTydefDpRP2qvDRaqfIT_R-Vk1eXpBLdpvkZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});